import '../styles/globals.css'
import Layout from "../components/Layout";
import Head from "next/head";
import '@fortawesome/fontawesome-svg-core/styles.css'

function MyApp({ Component, pageProps }) {
  return (
    <Layout>
      <Head>
        <title>Jorge S. Carrion - Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Layout>)
}

export default MyApp
